<?php

use Major\Fluent\Bundle\Types\FluentNumber;
use Major\Fluent\PluralRules\PluralRules;

it('works', function ($locale, $number, $minimumFractionDigits, $category) {
    expect(PluralRules::select(
        $locale, new FluentNumber($number, $minimumFractionDigits),
    ))->toBe($category);
})->with([
    ['en', 1, 0, 'one'],
    ['en', 0, 0, 'other'],
    ['en', 2, 0, 'other'],
    ['en', 16, 0, 'other'],
    ['en', 100, 0, 'other'],
    ['en', 1000, 0, 'other'],
    ['en', 0.0, 1, 'other'],
    ['en', 1.5, 1, 'other'],
    ['en', 10.0, 1, 'other'],
    ['en', 100.0, 1, 'other'],
    ['pl', 1, 0, 'one'],
    ['pl', 2, 0, 'few'],
    ['pl', 3, 0, 'few'],
    ['pl', 4, 0, 'few'],
    ['pl', 22, 0, 'few'],
    ['pl', 23, 0, 'few'],
    ['pl', 24, 0, 'few'],
    ['pl', 1002, 0, 'few'],
    ['pl', 1003, 0, 'few'],
    ['pl', 1004, 0, 'few'],
    ['pl', 0, 0, 'many'],
    ['pl', 5, 0, 'many'],
    ['pl', 6, 0, 'many'],
    ['pl', 8, 0, 'many'],
    ['pl', 17, 0, 'many'],
    ['pl', 19, 0, 'many'],
    ['pl', 10, 0, 'many'],
    ['pl', 100, 0, 'many'],
    ['pl', 1000, 0, 'many'],
    ['pl', 0.0, 1, 'other'],
    ['pl', 1.0, 1, 'other'],
    ['pl', 1.5, 1, 'other'],
    ['pl', 10.0, 1, 'other'],
    ['pl', 100.0, 1, 'other'],
    ['pl', 1000.0, 1, 'other'],
    ['de', 1.0, 0, 'one'],
    ['de', 1, 1, 'other'],
    ['de', 6.4, 0, 'other'],
    ['de', 32, 0, 'other'],
    ['he', 1, 0, 'one'],
    ['he', 2, 0, 'two'],
    ['he', 20, 0, 'many'],
    ['he', 30, 0, 'many'],
    ['he', 100, 0, 'many'],
    ['he', 3000, 0, 'many'],
    ['he', 0, 0, 'other'],
    ['he', 15, 0, 'other'],
    ['he', 101, 0, 'other'],
    ['he', 1, 2, 'other'],
    ['he', 2, 1, 'other'],
    ['he', 30, 1, 'other'],
    ['ga', 1, 0, 'one'],
    ['ga', 1, 1, 'one'],
    ['ga', 2, 0, 'two'],
    ['ga', 2, 1, 'two'],
    ['ga', 4, 0, 'few'],
    ['ga', 5, 1, 'few'],
    ['ga', 7, 0, 'many'],
    ['ga', 10, 1, 'many'],
    ['ga', 0, 0, 'other'],
    ['ga', 0, 1, 'other'],
    ['ga', 1.6, 0, 'other'],
    ['ga', 11, 0, 'other'],
    ['ga', 25, 0, 'other'],
    ['ga', 100, 0, 'other'],
    ['ga', 100, 1, 'other'],
    ['mk', 1, 0, 'one'],
    ['mk', 21, 0, 'one'],
    ['mk', 0.1, 0, 'one'],
    ['mk', 1.1, 0, 'one'],
    ['mk', 0, 0, 'other'],
    ['mk', 1.0, 1, 'other'],
    ['mk', 1.7, 1, 'other'],
    ['mk', 10, 1, 'other'],
]);
