#!/usr/bin/env php
<?php

use NunoMaduro\Collision\Provider;
use Symfony\Component\Console\Application;
use Major\Fluent\Dev\Commands;

require __DIR__ . '/vendor/autoload.php';

(new Provider())->register();

$application = new Application('fluent-php locale data compiler');

$application->addCommands([
    new Commands\CompileCurrenciesData(),
    new Commands\CompileNumbersData(),
]);

$application->run();
