#!/usr/bin/env php
<?php

use Major\Fluent\Dev;
use NunoMaduro\Collision\Provider;
use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';

(new Provider())->register();

$application = new Application('fluent-php locale data compiler');

$application->addCommands([
    new Dev\Currencies\CompileCurrenciesCommand(),
    new Dev\Locales\CompileLocalesCommand(),
]);

$application->run();
