<?php

use Major\Fluent\Formatters\Number\Locale\Unit as U;

return [
    'acre' => new U(name: 'area-acre', long: ['name' => 'فدان', 'plurals' => ['zero' => '{0} فدان', 'one' => 'فدان', 'two' => '{0} فدان', 'few' => '{0} أفدنة', 'many' => '{0} فدانًا', 'other' => '{0} فدان'], 'perUnit' => ''], short: ['name' => 'فدان', 'plurals' => ['zero' => '{0} فدان', 'one' => 'فدان', 'two' => 'فدانان', 'few' => '{0} أفدنة', 'many' => '{0} فدانًا', 'other' => '{0} فدان'], 'perUnit' => ''], narrow: ['name' => 'فدان', 'plurals' => ['zero' => '{0} فدان', 'one' => 'فدان', 'two' => 'فدانان', 'few' => '{0} أفدنة', 'many' => '{0} فدانًا', 'other' => '{0} فدان'], 'perUnit' => '']),
    'centimeter' => new U(name: 'length-centimeter', long: ['name' => 'سنتيمتر', 'plurals' => ['zero' => '{0} سنتيمتر', 'one' => '{0} سنتيمتر', 'two' => 'سنتيمتران', 'few' => '{0} سنتيمترات', 'many' => '{0} سنتيمترًا', 'other' => '{0} سنتيمتر'], 'perUnit' => '{0}/سنتيمتر'], short: ['name' => 'سم', 'plurals' => ['zero' => '{0} سم', 'one' => '{0} سم', 'two' => '{0} سم', 'few' => '{0} سم', 'many' => '{0} سم', 'other' => '{0} سم'], 'perUnit' => '{0}/سم'], narrow: ['name' => 'سم', 'plurals' => ['zero' => '{0} سم', 'one' => '{0} سم', 'two' => '{0} سم', 'few' => '{0} سم', 'many' => '{0} سم', 'other' => '{0} سم'], 'perUnit' => '{0}/سم']),
    'fluid-ounce' => new U(name: 'volume-fluid-ounce', long: ['name' => 'أونصة سائلة', 'plurals' => ['zero' => '{0} أونصة سائلة', 'one' => 'أونصة سائلة', 'two' => 'أونصتان سائلتان', 'few' => '{0} أونصة سائلة', 'many' => '{0} أونصة سائلة', 'other' => '{0} أونصة سائلة'], 'perUnit' => ''], short: ['name' => 'أونصة سائلة', 'plurals' => ['zero' => '{0} أونصة سائلة', 'one' => 'أونصة س', 'two' => 'أونصتان سائلتان', 'few' => '{0} أونصات سائلة', 'many' => '{0} أونصة س', 'other' => '{0} أونصة سائلة'], 'perUnit' => ''], narrow: ['name' => 'أونصة س', 'plurals' => ['zero' => '{0} أونصة س', 'one' => 'أونصة س', 'two' => 'أونصتان سائلتان', 'few' => '{0} أونصة س', 'many' => '{0} أونصة س', 'other' => '{0} أونصة س'], 'perUnit' => '']),
    'foot' => new U(name: 'length-foot', long: ['name' => 'قدم', 'plurals' => ['zero' => '{0} قدم', 'one' => 'قدم', 'two' => 'قدمان', 'few' => '{0} أقدام', 'many' => '{0} قدمًا', 'other' => '{0} قدم'], 'perUnit' => '{0} لكل قدم'], short: ['name' => 'قدم', 'plurals' => ['zero' => '{0} قدم', 'one' => 'قدم', 'two' => 'قدمان', 'few' => '{0} أقدام', 'many' => '{0} قدمًا', 'other' => '{0} قدم'], 'perUnit' => '{0}/قدم'], narrow: ['name' => 'قدم', 'plurals' => ['zero' => '{0} قدم', 'one' => 'قدم', 'two' => 'قدمان', 'few' => '{0} أقدام', 'many' => '{0} قدمًا', 'other' => '{0} قدم'], 'perUnit' => '{0}/قدم']),
    'gram' => new U(name: 'mass-gram', long: ['name' => 'غرام', 'plurals' => ['zero' => '{0} غرام', 'one' => 'غرام', 'two' => 'غرامان', 'few' => '{0} غرامات', 'many' => '{0} غرامًا', 'other' => '{0} غرام'], 'perUnit' => '{0}/غرام'], short: ['name' => 'غرام', 'plurals' => ['zero' => '{0} غرام', 'one' => 'غرام', 'two' => 'غرامان', 'few' => '{0} غرامات', 'many' => '{0} غرامًا', 'other' => '{0} غرام'], 'perUnit' => '{0}/غرام'], narrow: ['name' => 'غم', 'plurals' => ['zero' => '{0} غم', 'one' => '{0} غم', 'two' => '{0} غم', 'few' => '{0} غم', 'many' => '{0} غم', 'other' => '{0} غم'], 'perUnit' => '{0} غ']),
    'hectare' => new U(name: 'area-hectare', long: ['name' => 'هكتار', 'plurals' => ['zero' => '{0} هكتار', 'one' => '{0} هكتار', 'two' => 'هكتاران', 'few' => '{0} هكتارات', 'many' => '{0} هكتارًا', 'other' => '{0} هكتار'], 'perUnit' => ''], short: ['name' => 'هكتار', 'plurals' => ['zero' => '{0} هكتار', 'one' => '{0} هكتار', 'two' => 'هكتاران', 'few' => '{0} هكتارات', 'many' => '{0} هكتارًا', 'other' => '{0} هكتار'], 'perUnit' => ''], narrow: ['name' => 'هكتار', 'plurals' => ['zero' => '{0} هكتار', 'one' => '{0} هكتار', 'two' => 'هكتاران', 'few' => '{0} هكتارات', 'many' => '{0} هكتارًا', 'other' => '{0} هكتار'], 'perUnit' => '']),
    'inch' => new U(name: 'length-inch', long: ['name' => 'بوصة', 'plurals' => ['zero' => '{0} بوصة', 'one' => '{0} بوصة', 'two' => 'بوصتان', 'few' => '{0} بوصات', 'many' => '{0} بوصة', 'other' => '{0} بوصة'], 'perUnit' => '{0}/بوصة'], short: ['name' => 'بوصة', 'plurals' => ['zero' => '{0} بوصة', 'one' => '{0} بوصة', 'two' => 'بوصتان', 'few' => '{0} بوصات', 'many' => '{0} بوصة', 'other' => '{0} بوصة'], 'perUnit' => '{0}/بوصة'], narrow: ['name' => 'بوصة', 'plurals' => ['zero' => '{0} بوصة', 'one' => '{0} بوصة', 'two' => '{0} بوصة', 'few' => '{0} بوصة', 'many' => '{0} بوصة', 'other' => '{0} بوصة'], 'perUnit' => '{0}/بوصة']),
    'kilogram' => new U(name: 'mass-kilogram', long: ['name' => 'كيلوغرام', 'plurals' => ['zero' => '{0} كيلوغرام', 'one' => '{0} كيلوغرام', 'two' => 'كيلوغرامان', 'few' => '{0} كيلوغرامات', 'many' => '{0} كيلوغرامًا', 'other' => '{0} كيلوغرام'], 'perUnit' => '{0}/كيلوغرام'], short: ['name' => 'كغم', 'plurals' => ['zero' => '{0} كغم', 'one' => '{0} كغم', 'two' => '{0} كغم', 'few' => '{0} كغم', 'many' => '{0} كغم', 'other' => '{0} كغم'], 'perUnit' => '{0}/كغم'], narrow: ['name' => 'كغم', 'plurals' => ['zero' => '{0} كغم', 'one' => '{0} كغم', 'two' => '{0} كغم', 'few' => '{0} كغم', 'many' => '{0} كغم', 'other' => '{0} كغم'], 'perUnit' => '{0}/كغ']),
    'kilometer' => new U(name: 'length-kilometer', long: ['name' => 'كيلومتر', 'plurals' => ['zero' => '{0} كيلومتر', 'one' => '{0} كيلومتر', 'two' => 'كيلومتران', 'few' => '{0} كيلومترات', 'many' => '{0} كيلومترًا', 'other' => '{0} كيلومتر'], 'perUnit' => '{0}/كيلومتر'], short: ['name' => 'كم', 'plurals' => ['zero' => '{0} كم', 'one' => '{0} كم', 'two' => '{0} كم', 'few' => '{0} كم', 'many' => '{0} كم', 'other' => '{0} كم'], 'perUnit' => '{0}/كم'], narrow: ['name' => 'كم', 'plurals' => ['zero' => '{0} كم', 'one' => '{0} كم', 'two' => '{0} كم', 'few' => '{0} كم', 'many' => '{0} كم', 'other' => '{0} كم'], 'perUnit' => '{0}/كم']),
    'liter' => new U(name: 'volume-liter', long: ['name' => 'لتر', 'plurals' => ['zero' => '{0} لتر', 'one' => 'لتر', 'two' => 'لتران', 'few' => '{0} لترات', 'many' => '{0} لترًا', 'other' => '{0} لتر'], 'perUnit' => '{0} لكل لتر'], short: ['name' => 'لتر', 'plurals' => ['zero' => '{0} لتر', 'one' => 'لتر', 'two' => 'لتران', 'few' => '{0} لترات', 'many' => '{0} لترًا', 'other' => '{0} لتر'], 'perUnit' => '{0}/ل'], narrow: ['name' => 'لتر', 'plurals' => ['zero' => '{0} ل', 'one' => '{0} ل', 'two' => '{0} ل', 'few' => '{0} ل', 'many' => '{0} ل', 'other' => '{0} ل'], 'perUnit' => '{0}/ل']),
    'mile' => new U(name: 'length-mile', long: ['name' => 'ميل', 'plurals' => ['zero' => '{0} ميل', 'one' => 'ميل', 'two' => 'ميلان', 'few' => '{0} أميال', 'many' => '{0} ميلاً', 'other' => '{0} ميل'], 'perUnit' => ''], short: ['name' => 'ميل', 'plurals' => ['zero' => '{0} ميل', 'one' => 'ميل', 'two' => 'ميلان', 'few' => '{0} أميال', 'many' => '{0} ميل', 'other' => '{0} ميل'], 'perUnit' => ''], narrow: ['name' => 'ميل', 'plurals' => ['zero' => '{0} ميل', 'one' => '{0} ميل', 'two' => '{0} ميل', 'few' => '{0} أميال', 'many' => '{0} ميلاً', 'other' => '{0} ميل'], 'perUnit' => '']),
    'mile-scandinavian' => new U(name: 'length-mile-scandinavian', long: ['name' => 'ميل اسكندنافي', 'plurals' => ['zero' => '{0} ميل اسكندنافي', 'one' => '{0} ميل اسكندنافي', 'two' => 'ميلان اسكندنافيان', 'few' => '{0} أميال اسكندنافية', 'many' => '{0} ميلًا اسكندنافيًا', 'other' => '{0} ميل اسكندنافي'], 'perUnit' => ''], short: ['name' => 'ميل اسكندنافي', 'plurals' => ['zero' => '{0} ميل اسكندنافي', 'one' => '{0} ميل اسكندنافي', 'two' => 'ميلان اسكندنافيان', 'few' => '{0} أميال اسكندنافية', 'many' => '{0} ميلًا اسكندنافيًا', 'other' => '{0} ميل اسكندنافي'], 'perUnit' => ''], narrow: ['name' => 'ميل اسكندنافي', 'plurals' => ['zero' => '{0} ميل اسكندنافي', 'one' => '{0} ميل اسكندنافي', 'two' => 'ميلان اسكندنافيان', 'few' => '{0} أميال اسكندنافية', 'many' => '{0} ميلًا اسكندنافيًا', 'other' => '{0} ميل اسكندنافي'], 'perUnit' => '']),
    'millimeter' => new U(name: 'length-millimeter', long: ['name' => 'مليمتر', 'plurals' => ['zero' => '{0} مليمتر', 'one' => '{0} مليمتر', 'two' => 'مليمتران', 'few' => '{0} مليمتر', 'many' => '{0} مليمترًا', 'other' => '{0} مليمتر'], 'perUnit' => ''], short: ['name' => 'مليمتر', 'plurals' => ['zero' => '{0} مم', 'one' => '{0} مم', 'two' => '{0} مم', 'few' => '{0} مم', 'many' => '{0} مم', 'other' => '{0} مم'], 'perUnit' => ''], narrow: ['name' => 'مم', 'plurals' => ['zero' => '{0} مم', 'one' => '{0} مم', 'two' => '{0} مم', 'few' => '{0} مم', 'many' => '{0} مم', 'other' => '{0} مم'], 'perUnit' => '']),
    'pound' => new U(name: 'mass-pound', long: ['name' => 'رطل', 'plurals' => ['zero' => '{0} رطل', 'one' => '{0} رطل', 'two' => 'رطلان', 'few' => '{0} أرطال', 'many' => '{0} رطلًا', 'other' => '{0} رطل'], 'perUnit' => '{0}/رطل'], short: ['name' => 'رطل', 'plurals' => ['zero' => '{0} رطل', 'one' => '{0} رطل', 'two' => 'رطلان', 'few' => '{0} أرطال', 'many' => '{0} رطلُا', 'other' => '{0} رطل'], 'perUnit' => '{0}/رطل'], narrow: ['name' => 'رطل', 'plurals' => ['zero' => '{0} رطل', 'one' => '{0} رطل', 'two' => 'رطلان', 'few' => '{0} أرطال', 'many' => '{0} رطلُا', 'other' => '{0} رطل'], 'perUnit' => '{0}/رطل']),
    'second' => new U(name: 'duration-second', long: ['name' => 'ثانية', 'plurals' => ['zero' => '{0} ثانية', 'one' => 'ثانية', 'two' => 'ثانيتان', 'few' => '{0} ثوانٍ', 'many' => '{0} ثانية', 'other' => '{0} ثانية'], 'perUnit' => '{0} في الثانية'], short: ['name' => 'ثانية', 'plurals' => ['zero' => '{0} ث', 'one' => '{0} ث', 'two' => '{0} ث', 'few' => '{0} ث', 'many' => '{0} ث', 'other' => '{0} ث'], 'perUnit' => '{0}/ث'], narrow: ['name' => 'ث', 'plurals' => ['zero' => '{0} ث', 'one' => '{0} ث', 'two' => '{0} ث', 'few' => '{0} ث', 'many' => '{0} ث', 'other' => '{0} ث'], 'perUnit' => '{0}/ث']),
    'yard' => new U(name: 'length-yard', long: ['name' => 'ياردة', 'plurals' => ['zero' => '{0} ياردة', 'one' => 'ياردة', 'two' => 'ياردتان', 'few' => '{0} ياردات', 'many' => '{0} ياردة', 'other' => '{0} ياردة'], 'perUnit' => ''], short: ['name' => 'ياردة', 'plurals' => ['zero' => '{0} ياردة', 'one' => 'ياردة', 'two' => 'ياردتان', 'few' => '{0} ياردات', 'many' => '{0} ياردة', 'other' => '{0} ياردة'], 'perUnit' => ''], narrow: ['name' => 'ياردة', 'plurals' => ['zero' => '{0} ياردة', 'one' => '{0} ياردة', 'two' => 'ياردتان', 'few' => '{0} ياردة', 'many' => '{0} ياردة', 'other' => '{0} ياردة'], 'perUnit' => '']),
    'year' => new U(name: 'duration-year', long: ['name' => 'سنوات', 'plurals' => ['zero' => '{0} سنة', 'one' => 'سنة', 'two' => 'سنتان', 'few' => '{0} سنوات', 'many' => '{0} سنة', 'other' => '{0} سنة'], 'perUnit' => '{0} في السنة'], short: ['name' => 'سنوات', 'plurals' => ['zero' => '{0} سنة', 'one' => 'سنة', 'two' => 'سنتان', 'few' => '{0} سنوات', 'many' => '{0} سنة', 'other' => '{0} سنة'], 'perUnit' => '{0}/سنة'], narrow: ['name' => 'سنة', 'plurals' => ['zero' => '{0} سنة', 'one' => 'سنة', 'two' => 'سنتان', 'few' => '{0} سنوات', 'many' => '{0} سنة', 'other' => '{0} سنة'], 'perUnit' => '{0}/سنة']),
];
