<?php

use Major\Fluent\Formatters\Number\Locale\Unit as U;

return [
    'day' => new U(name: 'duration-day', long: ['name' => 'суткі', 'plurals' => ['one' => '{0} суткі', 'few' => '{0} сутак', 'many' => '{0} сутак', 'other' => '{0} сутак'], 'perUnit' => '{0} у суткі'], short: ['name' => 'сут', 'plurals' => ['one' => '{0} сут', 'few' => '{0} сут', 'many' => '{0} сут', 'other' => '{0} сут'], 'perUnit' => '{0} сут'], narrow: ['name' => 'сут', 'plurals' => ['one' => '{0} сут', 'few' => '{0} сут', 'many' => '{0} сут', 'other' => '{0} сут'], 'perUnit' => '{0} сут.']),
    'hour' => new U(name: 'duration-hour', long: ['name' => 'гадзіны', 'plurals' => ['one' => '{0} гадзіна', 'few' => '{0} гадзіны', 'many' => '{0} гадзін', 'other' => '{0} гадзіны'], 'perUnit' => '{0} у гадзіну'], short: ['name' => 'гадз', 'plurals' => ['one' => '{0} гадз', 'few' => '{0} гадз', 'many' => '{0} гадз', 'other' => '{0} гадз'], 'perUnit' => '{0}/гадз'], narrow: ['name' => 'гадз', 'plurals' => ['one' => '{0} гадз', 'few' => '{0} гадз', 'many' => '{0} гадз', 'other' => '{0} гадз'], 'perUnit' => '{0}/гадз.']),
    'minute' => new U(name: 'duration-minute', long: ['name' => 'хвіліны', 'plurals' => ['one' => '{0} хвіліна', 'few' => '{0} хвіліны', 'many' => '{0} хвілін', 'other' => '{0} хвіліны'], 'perUnit' => '{0} у хвіліну'], short: ['name' => 'хв', 'plurals' => ['one' => '{0} хв', 'few' => '{0} хв', 'many' => '{0} хв', 'other' => '{0} хв'], 'perUnit' => '{0}/ хв'], narrow: ['name' => 'хв', 'plurals' => ['one' => '{0} хв', 'few' => '{0} хв', 'many' => '{0} хв', 'other' => '{0} хв'], 'perUnit' => '{0}/ хв.']),
    'second' => new U(name: 'duration-second', long: ['name' => 'секунды', 'plurals' => ['one' => '{0} секунда', 'few' => '{0} секунды', 'many' => '{0} секунд', 'other' => '{0} секунды'], 'perUnit' => '{0} у секунду'], short: ['name' => 'с', 'plurals' => ['one' => '{0} с', 'few' => '{0} с', 'many' => '{0} с', 'other' => '{0} с'], 'perUnit' => '{0}/с'], narrow: ['name' => 'с', 'plurals' => ['one' => '{0} с', 'few' => '{0} с', 'many' => '{0} с', 'other' => '{0} с'], 'perUnit' => '{0}/сэк.']),
];
