<?php

use Major\Fluent\Formatters\Number\Locale\Unit as U;

return [
    'celsius' => new U(name: 'temperature-celsius', long: ['name' => 'degrees Celsius', 'plurals' => ['one' => '{0} degree Celsius', 'other' => '{0} degrees Celsius'], 'perUnit' => ''], short: ['name' => 'deg C', 'plurals' => ['one' => '{0}°C', 'other' => '{0}°C'], 'perUnit' => ''], narrow: ['name' => '°C', 'plurals' => ['one' => '{0}°C', 'other' => '{0}°C'], 'perUnit' => '']),
    'centimeter' => new U(name: 'length-centimeter', long: ['name' => 'centimetres', 'plurals' => ['one' => '{0} centimetre', 'other' => '{0} centimetres'], 'perUnit' => '{0} per centimetre'], short: ['name' => 'cm', 'plurals' => ['one' => '{0} cm', 'other' => '{0} cm'], 'perUnit' => '{0}/cm'], narrow: ['name' => 'cm', 'plurals' => ['one' => '{0}cm', 'other' => '{0}cm'], 'perUnit' => '{0}/cm']),
    'fahrenheit' => new U(name: 'temperature-fahrenheit', long: ['name' => 'degrees Fahrenheit', 'plurals' => ['one' => '{0} degree Fahrenheit', 'other' => '{0} degrees Fahrenheit'], 'perUnit' => ''], short: ['name' => 'deg F', 'plurals' => ['one' => '{0}°F', 'other' => '{0}°F'], 'perUnit' => ''], narrow: ['name' => '°F', 'plurals' => ['one' => '{0}°F', 'other' => '{0}°F'], 'perUnit' => '']),
    'gallon' => new U(name: 'volume-gallon', long: ['name' => 'US gallons', 'plurals' => ['one' => '{0} US gallon', 'other' => '{0} US gallons'], 'perUnit' => '{0} per US gallon'], short: ['name' => 'gal US', 'plurals' => ['one' => '{0} gal US', 'other' => '{0} gal US'], 'perUnit' => '{0}/gal US'], narrow: ['name' => 'gal US', 'plurals' => ['one' => '{0} gal US', 'other' => '{0} gal US'], 'perUnit' => '{0}/galUS']),
    'hour' => new U(name: 'duration-hour', long: ['name' => 'hours', 'plurals' => ['one' => '{0} hour', 'other' => '{0} hours'], 'perUnit' => '{0} per hour'], short: ['name' => 'hours', 'plurals' => ['one' => '{0} hr', 'other' => '{0} hrs'], 'perUnit' => '{0}/h'], narrow: ['name' => 'hour', 'plurals' => ['one' => '{0}h', 'other' => '{0}h'], 'perUnit' => '{0}/h']),
    'kilometer' => new U(name: 'length-kilometer', long: ['name' => 'kilometre', 'plurals' => ['one' => '{0} kilometre', 'other' => '{0} kilometres'], 'perUnit' => '{0} per kilometre'], short: ['name' => 'km', 'plurals' => ['one' => '{0} km', 'other' => '{0} km'], 'perUnit' => '{0}/km'], narrow: ['name' => 'km', 'plurals' => ['one' => '{0}km', 'other' => '{0}km'], 'perUnit' => '{0}/km']),
    'liter' => new U(name: 'volume-liter', long: ['name' => 'litres', 'plurals' => ['one' => '{0} litre', 'other' => '{0} litres'], 'perUnit' => '{0} per litre'], short: ['name' => 'litres', 'plurals' => ['one' => '{0} L', 'other' => '{0} L'], 'perUnit' => '{0}/L'], narrow: ['name' => 'litre', 'plurals' => ['one' => '{0}L', 'other' => '{0}L'], 'perUnit' => '{0}/L']),
    'meter' => new U(name: 'length-meter', long: ['name' => 'metres', 'plurals' => ['one' => '{0} metre', 'other' => '{0} metres'], 'perUnit' => '{0} per metre'], short: ['name' => 'metres', 'plurals' => ['one' => '{0} m', 'other' => '{0} m'], 'perUnit' => '{0}/m'], narrow: ['name' => 'metre', 'plurals' => ['one' => '{0}m', 'other' => '{0}m'], 'perUnit' => '{0}/m']),
    'mile-scandinavian' => new U(name: 'length-mile-scandinavian', long: ['name' => 'Scandinavian mile', 'plurals' => ['one' => '{0} Scandinavian mile', 'other' => '{0} Scandinavian miles'], 'perUnit' => ''], short: ['name' => 'smi', 'plurals' => ['one' => '{0} smi', 'other' => '{0} smi'], 'perUnit' => ''], narrow: ['name' => 'smi', 'plurals' => ['one' => '{0}smi', 'other' => '{0}smi'], 'perUnit' => '']),
    'milliliter' => new U(name: 'volume-milliliter', long: ['name' => 'millilitres', 'plurals' => ['one' => '{0} millilitre', 'other' => '{0} millilitres'], 'perUnit' => ''], short: ['name' => 'mL', 'plurals' => ['one' => '{0} mL', 'other' => '{0} mL'], 'perUnit' => ''], narrow: ['name' => 'mL', 'plurals' => ['one' => '{0}mL', 'other' => '{0}mL'], 'perUnit' => '']),
    'millimeter' => new U(name: 'length-millimeter', long: ['name' => 'millimetres', 'plurals' => ['one' => '{0} millimetre', 'other' => '{0} millimetres'], 'perUnit' => ''], short: ['name' => 'mm', 'plurals' => ['one' => '{0} mm', 'other' => '{0} mm'], 'perUnit' => ''], narrow: ['name' => 'mm', 'plurals' => ['one' => '{0}mm', 'other' => '{0}mm'], 'perUnit' => '']),
    'millisecond' => new U(name: 'duration-millisecond', long: ['name' => 'milliseconds', 'plurals' => ['one' => '{0} millisecond', 'other' => '{0} milliseconds'], 'perUnit' => ''], short: ['name' => 'millisec.', 'plurals' => ['one' => '{0} ms', 'other' => '{0} ms'], 'perUnit' => ''], narrow: ['name' => 'msec.', 'plurals' => ['one' => '{0}ms', 'other' => '{0}ms'], 'perUnit' => '']),
    'minute' => new U(name: 'duration-minute', long: ['name' => 'minutes', 'plurals' => ['one' => '{0} minute', 'other' => '{0} minutes'], 'perUnit' => '{0} per minute'], short: ['name' => 'min.', 'plurals' => ['one' => '{0} min.', 'other' => '{0} mins'], 'perUnit' => '{0}/min.'], narrow: ['name' => 'min.', 'plurals' => ['one' => '{0}min.', 'other' => '{0}min.'], 'perUnit' => '{0}/min.']),
    'percent' => new U(name: 'concentr-percent', long: ['name' => 'per cent', 'plurals' => ['one' => '{0} per cent', 'other' => '{0} per cent'], 'perUnit' => ''], short: ['name' => 'per cent', 'plurals' => ['one' => '{0}%', 'other' => '{0}%'], 'perUnit' => ''], narrow: ['name' => '%', 'plurals' => ['one' => '{0}%', 'other' => '{0}%'], 'perUnit' => '']),
    'pound' => new U(name: 'mass-pound', long: ['name' => 'pounds', 'plurals' => ['one' => '{0} pound', 'other' => '{0} pounds'], 'perUnit' => '{0} per pound'], short: ['name' => 'pounds', 'plurals' => ['one' => '{0} lb', 'other' => '{0} lb'], 'perUnit' => '{0}/lb'], narrow: ['name' => 'lb', 'plurals' => ['one' => '{0}lb', 'other' => '{0}lb'], 'perUnit' => '{0}/lb']),
    'second' => new U(name: 'duration-second', long: ['name' => 'seconds', 'plurals' => ['one' => '{0} second', 'other' => '{0} seconds'], 'perUnit' => '{0} per second'], short: ['name' => 'sec.', 'plurals' => ['one' => '{0} sec.', 'other' => '{0} secs'], 'perUnit' => '{0} ps.'], narrow: ['name' => 'sec.', 'plurals' => ['one' => '{0}s.', 'other' => '{0}s.'], 'perUnit' => '{0} ps.']),
    'stone' => new U(name: 'mass-stone', long: ['name' => 'stone', 'plurals' => ['one' => '{0} stone', 'other' => '{0} stone'], 'perUnit' => ''], short: ['name' => 'stone', 'plurals' => ['one' => '{0} st', 'other' => '{0} st'], 'perUnit' => ''], narrow: ['name' => 'stone', 'plurals' => ['one' => '{0}st', 'other' => '{0}st'], 'perUnit' => '']),
];
