<?php

use Major\Fluent\Formatters\Number\Locale\Unit as U;

return [
    'kilometer' => new U(name: 'length-kilometer', long: ['name' => 'kilometres', 'plurals' => ['one' => '{0} kilometre', 'other' => '{0} kilometres'], 'perUnit' => '{0} per kilometre'], short: ['name' => 'km', 'plurals' => ['one' => '{0} km', 'other' => '{0} km'], 'perUnit' => '{0}/km'], narrow: ['name' => 'km', 'plurals' => ['one' => '{0}km', 'other' => '{0}km'], 'perUnit' => '{0}/km']),
    'bit' => new U(name: 'digital-bit', long: ['name' => 'bits', 'plurals' => ['one' => '{0} bit', 'other' => '{0} bits'], 'perUnit' => ''], short: ['name' => 'bits', 'plurals' => ['one' => '{0} bit', 'other' => '{0} bits'], 'perUnit' => ''], narrow: ['name' => 'bit', 'plurals' => ['one' => '{0}bit', 'other' => '{0}bits'], 'perUnit' => '']),
    'byte' => new U(name: 'digital-byte', long: ['name' => 'bytes', 'plurals' => ['one' => '{0} byte', 'other' => '{0} bytes'], 'perUnit' => ''], short: ['name' => 'bytes', 'plurals' => ['one' => '{0} byte', 'other' => '{0} bytes'], 'perUnit' => ''], narrow: ['name' => 'B', 'plurals' => ['one' => '{0}B', 'other' => '{0}B'], 'perUnit' => '']),
    'hour' => new U(name: 'duration-hour', long: ['name' => 'hours', 'plurals' => ['one' => '{0} hour', 'other' => '{0} hours'], 'perUnit' => '{0} per hour'], short: ['name' => 'hours', 'plurals' => ['one' => '{0} hr', 'other' => '{0} hrs'], 'perUnit' => '{0}/hr'], narrow: ['name' => 'hour', 'plurals' => ['one' => '{0}h', 'other' => '{0}h'], 'perUnit' => '{0}/hr']),
    'millisecond' => new U(name: 'duration-millisecond', long: ['name' => 'milliseconds', 'plurals' => ['one' => '{0} millisecond', 'other' => '{0} milliseconds'], 'perUnit' => ''], short: ['name' => 'millisecs', 'plurals' => ['one' => '{0} millisec', 'other' => '{0} millisecs'], 'perUnit' => ''], narrow: ['name' => 'msec', 'plurals' => ['one' => '{0}ms', 'other' => '{0}ms'], 'perUnit' => '']),
    'minute' => new U(name: 'duration-minute', long: ['name' => 'minutes', 'plurals' => ['one' => '{0} minute', 'other' => '{0} minutes'], 'perUnit' => '{0} per minute'], short: ['name' => 'mins', 'plurals' => ['one' => '{0} min', 'other' => '{0} mins'], 'perUnit' => '{0}/min'], narrow: ['name' => 'min', 'plurals' => ['one' => '{0}min', 'other' => '{0}min'], 'perUnit' => '{0}/min']),
    'month' => new U(name: 'duration-month', long: ['name' => 'months', 'plurals' => ['one' => '{0} month', 'other' => '{0} months'], 'perUnit' => '{0} per month'], short: ['name' => 'months', 'plurals' => ['one' => '{0} mo', 'other' => '{0} mos'], 'perUnit' => '{0}/mo'], narrow: ['name' => 'month', 'plurals' => ['one' => '{0}m', 'other' => '{0}m'], 'perUnit' => '{0}/mo']),
    'second' => new U(name: 'duration-second', long: ['name' => 'seconds', 'plurals' => ['one' => '{0} second', 'other' => '{0} seconds'], 'perUnit' => '{0} per second'], short: ['name' => 'secs', 'plurals' => ['one' => '{0} sec', 'other' => '{0} secs'], 'perUnit' => '{0}/sec'], narrow: ['name' => 'sec', 'plurals' => ['one' => '{0}s', 'other' => '{0}s'], 'perUnit' => '{0}/sec']),
    'week' => new U(name: 'duration-week', long: ['name' => 'weeks', 'plurals' => ['one' => '{0} week', 'other' => '{0} weeks'], 'perUnit' => '{0} per week'], short: ['name' => 'weeks', 'plurals' => ['one' => '{0} wk', 'other' => '{0} wks'], 'perUnit' => '{0}/wk'], narrow: ['name' => 'wk', 'plurals' => ['one' => '{0}w', 'other' => '{0}w'], 'perUnit' => '{0}/wk']),
    'year' => new U(name: 'duration-year', long: ['name' => 'years', 'plurals' => ['one' => '{0} year', 'other' => '{0} years'], 'perUnit' => '{0} per year'], short: ['name' => 'years', 'plurals' => ['one' => '{0} yr', 'other' => '{0} yrs'], 'perUnit' => '{0}/yr'], narrow: ['name' => 'yr', 'plurals' => ['one' => '{0}y', 'other' => '{0}y'], 'perUnit' => '{0}/yr']),
    'centimeter' => new U(name: 'length-centimeter', long: ['name' => 'centimetres', 'plurals' => ['one' => '{0} centimetre', 'other' => '{0} centimetres'], 'perUnit' => '{0} per centimetre'], short: ['name' => 'cm', 'plurals' => ['one' => '{0} cm', 'other' => '{0} cm'], 'perUnit' => '{0}/cm'], narrow: ['name' => 'cm', 'plurals' => ['one' => '{0}cm', 'other' => '{0}cm'], 'perUnit' => '{0}/cm']),
    'meter' => new U(name: 'length-meter', long: ['name' => 'metres', 'plurals' => ['one' => '{0} metre', 'other' => '{0} metres'], 'perUnit' => '{0} per metre'], short: ['name' => 'metres', 'plurals' => ['one' => '{0} m', 'other' => '{0} m'], 'perUnit' => '{0}/m'], narrow: ['name' => 'metre', 'plurals' => ['one' => '{0}m', 'other' => '{0}m'], 'perUnit' => '{0}/m']),
    'mile-scandinavian' => new U(name: 'length-mile-scandinavian', long: ['name' => 'Scandinavian mile', 'plurals' => ['one' => '{0} Scandinavian mile', 'other' => '{0} Scandinavian miles'], 'perUnit' => ''], short: ['name' => 'smi', 'plurals' => ['one' => '{0} smi', 'other' => '{0} smi'], 'perUnit' => ''], narrow: ['name' => 'smi', 'plurals' => ['one' => '{0}smi', 'other' => '{0}smi'], 'perUnit' => '']),
    'millimeter' => new U(name: 'length-millimeter', long: ['name' => 'millimetres', 'plurals' => ['one' => '{0} millimetre', 'other' => '{0} millimetres'], 'perUnit' => ''], short: ['name' => 'mm', 'plurals' => ['one' => '{0} mm', 'other' => '{0} mm'], 'perUnit' => ''], narrow: ['name' => 'mm', 'plurals' => ['one' => '{0}mm', 'other' => '{0}mm'], 'perUnit' => '']),
    'pound' => new U(name: 'mass-pound', long: ['name' => 'pounds', 'plurals' => ['one' => '{0} pound', 'other' => '{0} pounds'], 'perUnit' => '{0} per pound'], short: ['name' => 'pounds', 'plurals' => ['one' => '{0} lb', 'other' => '{0} lb'], 'perUnit' => '{0}/lb'], narrow: ['name' => 'lb', 'plurals' => ['one' => '{0}lb', 'other' => '{0}lb'], 'perUnit' => '{0}/lb']),
    'stone' => new U(name: 'mass-stone', long: ['name' => 'stone', 'plurals' => ['one' => '{0} stone', 'other' => '{0} stone'], 'perUnit' => ''], short: ['name' => 'stone', 'plurals' => ['one' => '{0} st', 'other' => '{0} st'], 'perUnit' => ''], narrow: ['name' => 'stone', 'plurals' => ['one' => '{0}st', 'other' => '{0}st'], 'perUnit' => '']),
    'celsius' => new U(name: 'temperature-celsius', long: ['name' => 'degrees Celsius', 'plurals' => ['one' => '{0} degree Celsius', 'other' => '{0} degrees Celsius'], 'perUnit' => ''], short: ['name' => 'deg C', 'plurals' => ['one' => '{0} °C', 'other' => '{0} °C'], 'perUnit' => ''], narrow: ['name' => '°C', 'plurals' => ['one' => '{0}°', 'other' => '{0}°'], 'perUnit' => '']),
    'fahrenheit' => new U(name: 'temperature-fahrenheit', long: ['name' => 'degrees Fahrenheit', 'plurals' => ['one' => '{0} degree Fahrenheit', 'other' => '{0} degrees Fahrenheit'], 'perUnit' => ''], short: ['name' => 'deg F', 'plurals' => ['one' => '{0} °F', 'other' => '{0} °F'], 'perUnit' => ''], narrow: ['name' => '°F', 'plurals' => ['one' => '{0}°F', 'other' => '{0}°F'], 'perUnit' => '']),
    'fluid-ounce' => new U(name: 'volume-fluid-ounce', long: ['name' => 'US fluid ounces', 'plurals' => ['one' => '{0} US fluid ounce', 'other' => '{0} US fluid ounces'], 'perUnit' => ''], short: ['name' => 'US fl oz', 'plurals' => ['one' => '{0} US fl oz', 'other' => '{0} US fl oz'], 'perUnit' => ''], narrow: ['name' => 'US fl oz', 'plurals' => ['one' => '{0}US fl oz', 'other' => '{0}US fl oz'], 'perUnit' => '']),
    'gallon' => new U(name: 'volume-gallon', long: ['name' => 'US gallons', 'plurals' => ['one' => '{0} US gallon', 'other' => '{0} US gallons'], 'perUnit' => '{0} per US gallon'], short: ['name' => 'US gal', 'plurals' => ['one' => '{0} US gal', 'other' => '{0} US gal'], 'perUnit' => '{0}/US gal'], narrow: ['name' => 'US gal', 'plurals' => ['one' => '{0}USgal', 'other' => '{0}USgal'], 'perUnit' => '{0}/USgal']),
    'liter' => new U(name: 'volume-liter', long: ['name' => 'litres', 'plurals' => ['one' => '{0} litre', 'other' => '{0} litres'], 'perUnit' => '{0} per litre'], short: ['name' => 'litres', 'plurals' => ['one' => '{0} L', 'other' => '{0} L'], 'perUnit' => '{0}/L'], narrow: ['name' => 'litre', 'plurals' => ['one' => '{0}L', 'other' => '{0}L'], 'perUnit' => '{0}/L']),
    'milliliter' => new U(name: 'volume-milliliter', long: ['name' => 'millilitres', 'plurals' => ['one' => '{0} millilitre', 'other' => '{0} millilitres'], 'perUnit' => ''], short: ['name' => 'mL', 'plurals' => ['one' => '{0} mL', 'other' => '{0} mL'], 'perUnit' => ''], narrow: ['name' => 'mL', 'plurals' => ['one' => '{0}mL', 'other' => '{0}mL'], 'perUnit' => '']),
];
