<?php

use Major\Fluent\Formatters\Number\Locale\Unit as U;

return [
    'celsius' => new U(long: ['name' => 'degrees Celsius', 'plurals' => ['one' => '{0} degree Celsius', 'other' => '{0} degrees Celsius'], 'perUnit' => ''], short: ['name' => 'deg. C', 'plurals' => ['one' => '{0}°C', 'other' => '{0}°C'], 'perUnit' => ''], narrow: ['name' => '°C', 'plurals' => ['one' => '{0}°', 'other' => '{0}°'], 'perUnit' => '']),
    'centimeter' => new U(long: ['name' => 'centimetres', 'plurals' => ['one' => '{0} centimetre', 'other' => '{0} centimetres'], 'perUnit' => '{0} per centimetre'], short: ['name' => 'cm', 'plurals' => ['one' => '{0} cm', 'other' => '{0} cm'], 'perUnit' => '{0}/cm'], narrow: ['name' => 'cm', 'plurals' => ['one' => '{0}cm', 'other' => '{0}cm'], 'perUnit' => '{0}/cm']),
    'fahrenheit' => new U(long: ['name' => 'degrees Fahrenheit', 'plurals' => ['one' => '{0} degree Fahrenheit', 'other' => '{0} degrees Fahrenheit'], 'perUnit' => ''], short: ['name' => 'deg. F', 'plurals' => ['one' => '{0}°F', 'other' => '{0}°F'], 'perUnit' => ''], narrow: ['name' => '°F', 'plurals' => ['one' => '{0}°F', 'other' => '{0}°F'], 'perUnit' => '']),
    'fluid-ounce' => new U(long: ['name' => 'US fluid ounces', 'plurals' => ['one' => '{0} US fluid ounce', 'other' => '{0} US fluid ounces'], 'perUnit' => ''], short: ['name' => 'US fl oz', 'plurals' => ['one' => '{0} US fl oz', 'other' => '{0} US fl oz'], 'perUnit' => ''], narrow: ['name' => 'US fl oz', 'plurals' => ['one' => '{0}US fl oz', 'other' => '{0}US fl oz'], 'perUnit' => '']),
    'gallon' => new U(long: ['name' => 'US gallons', 'plurals' => ['one' => '{0} US gallon', 'other' => '{0} US gallons'], 'perUnit' => '{0} per US gallon'], short: ['name' => 'US gal', 'plurals' => ['one' => '{0} US gal', 'other' => '{0} US gal'], 'perUnit' => '{0}/US gal'], narrow: ['name' => 'US gal', 'plurals' => ['one' => '{0}galUS', 'other' => '{0}galUS'], 'perUnit' => '{0}/galUS']),
    'hour' => new U(long: ['name' => 'hours', 'plurals' => ['one' => '{0} hour', 'other' => '{0} hours'], 'perUnit' => '{0} per hour'], short: ['name' => 'hours', 'plurals' => ['one' => '{0} hr', 'other' => '{0} hrs'], 'perUnit' => '{0}/h'], narrow: ['name' => 'hour', 'plurals' => ['one' => '{0}h', 'other' => '{0}h'], 'perUnit' => '{0}/h']),
    'kilometer' => new U(long: ['name' => 'kilometres', 'plurals' => ['one' => '{0} kilometre', 'other' => '{0} kilometres'], 'perUnit' => '{0} per kilometre'], short: ['name' => 'km', 'plurals' => ['one' => '{0} km', 'other' => '{0} km'], 'perUnit' => '{0}/km'], narrow: ['name' => 'km', 'plurals' => ['one' => '{0}km', 'other' => '{0}km'], 'perUnit' => '{0}/km']),
    'liter' => new U(long: ['name' => 'litres', 'plurals' => ['one' => '{0} litre', 'other' => '{0} litres'], 'perUnit' => '{0} per litre'], short: ['name' => 'litres', 'plurals' => ['one' => '{0} l', 'other' => '{0} l'], 'perUnit' => '{0}/l'], narrow: ['name' => 'litre', 'plurals' => ['one' => '{0}l', 'other' => '{0}l'], 'perUnit' => '{0}/l']),
    'meter' => new U(long: ['name' => 'metres', 'plurals' => ['one' => '{0} metre', 'other' => '{0} metres'], 'perUnit' => '{0} per metre'], short: ['name' => 'metres', 'plurals' => ['one' => '{0} m', 'other' => '{0} m'], 'perUnit' => '{0}/m'], narrow: ['name' => 'metre', 'plurals' => ['one' => '{0}m', 'other' => '{0}m'], 'perUnit' => '{0}/m']),
    'mile-scandinavian' => new U(long: ['name' => 'Scandinavian mile', 'plurals' => ['one' => '{0} Scandinavian mile', 'other' => '{0} Scandinavian miles'], 'perUnit' => ''], short: ['name' => 'smi', 'plurals' => ['one' => '{0} smi', 'other' => '{0} smi'], 'perUnit' => ''], narrow: ['name' => 'smi', 'plurals' => ['one' => '{0}smi', 'other' => '{0}smi'], 'perUnit' => '']),
    'milliliter' => new U(long: ['name' => 'millilitres', 'plurals' => ['one' => '{0} millilitre', 'other' => '{0} millilitres'], 'perUnit' => ''], short: ['name' => 'ml', 'plurals' => ['one' => '{0} ml', 'other' => '{0} ml'], 'perUnit' => ''], narrow: ['name' => 'ml', 'plurals' => ['one' => '{0}ml', 'other' => '{0}ml'], 'perUnit' => '']),
    'millimeter' => new U(long: ['name' => 'millimetres', 'plurals' => ['one' => '{0} millimetre', 'other' => '{0} millimetres'], 'perUnit' => ''], short: ['name' => 'mm', 'plurals' => ['one' => '{0} mm', 'other' => '{0} mm'], 'perUnit' => ''], narrow: ['name' => 'mm', 'plurals' => ['one' => '{0}mm', 'other' => '{0}mm'], 'perUnit' => '']),
    'minute' => new U(long: ['name' => 'minutes', 'plurals' => ['one' => '{0} minute', 'other' => '{0} minutes'], 'perUnit' => '{0} per minute'], short: ['name' => 'mins', 'plurals' => ['one' => '{0} min', 'other' => '{0} mins'], 'perUnit' => '{0}/min'], narrow: ['name' => 'min', 'plurals' => ['one' => '{0}m', 'other' => '{0}m'], 'perUnit' => '{0}/min']),
    'percent' => new U(long: ['name' => 'per cent', 'plurals' => ['one' => '{0} per cent', 'other' => '{0} per cent'], 'perUnit' => ''], short: ['name' => 'per cent', 'plurals' => ['one' => '{0}%', 'other' => '{0}%'], 'perUnit' => ''], narrow: ['name' => '%', 'plurals' => ['one' => '{0}%', 'other' => '{0}%'], 'perUnit' => '']),
    'pound' => new U(long: ['name' => 'pounds', 'plurals' => ['one' => '{0} pound', 'other' => '{0} pounds'], 'perUnit' => '{0} per pound'], short: ['name' => 'pounds', 'plurals' => ['one' => '{0} lb', 'other' => '{0} lb'], 'perUnit' => '{0}/lb'], narrow: ['name' => 'lb', 'plurals' => ['one' => '{0}lb', 'other' => '{0}lb'], 'perUnit' => '{0}/lb']),
    'second' => new U(long: ['name' => 'seconds', 'plurals' => ['one' => '{0} second', 'other' => '{0} seconds'], 'perUnit' => '{0} per second'], short: ['name' => 'secs', 'plurals' => ['one' => '{0} sec', 'other' => '{0} secs'], 'perUnit' => '{0}/s'], narrow: ['name' => 'sec', 'plurals' => ['one' => '{0}s', 'other' => '{0}s'], 'perUnit' => '{0}/s']),
    'stone' => new U(long: ['name' => 'stone', 'plurals' => ['one' => '{0} stone', 'other' => '{0} stone'], 'perUnit' => ''], short: ['name' => 'stone', 'plurals' => ['one' => '{0} st', 'other' => '{0} st'], 'perUnit' => ''], narrow: ['name' => 'stone', 'plurals' => ['one' => '{0}st', 'other' => '{0}st'], 'perUnit' => '']),
];
