<?php

use Major\Fluent\Formatters\Number\Locale\Unit as U;

return [
    'acre' => new U(name: 'area-acre', long: ['name' => 'acres', 'plurals' => ['one' => '{0} acre', 'other' => '{0} acres'], 'perUnit' => ''], short: ['name' => 'acres', 'plurals' => ['one' => '{0} acre', 'other' => '{0} acres'], 'perUnit' => ''], narrow: ['name' => 'acre', 'plurals' => ['one' => '{0} acre', 'other' => '{0} acres'], 'perUnit' => '']),
    'bit' => new U(name: 'digital-bit', long: ['name' => 'bits', 'plurals' => ['one' => '{0} bit', 'other' => '{0} bits'], 'perUnit' => ''], short: ['name' => 'bit', 'plurals' => ['one' => '{0} bit', 'other' => '{0} bit'], 'perUnit' => ''], narrow: ['name' => 'bit', 'plurals' => ['one' => '{0} bit', 'other' => '{0} bit'], 'perUnit' => '']),
    'byte' => new U(name: 'digital-byte', long: ['name' => 'bytes', 'plurals' => ['one' => '{0} byte', 'other' => '{0} bytes'], 'perUnit' => ''], short: ['name' => 'byte', 'plurals' => ['one' => '{0} byte', 'other' => '{0} byte'], 'perUnit' => ''], narrow: ['name' => 'B', 'plurals' => ['one' => '{0} B', 'other' => '{0} B'], 'perUnit' => '']),
    'celsius' => new U(name: 'temperature-celsius', long: ['name' => 'graus Celsius', 'plurals' => ['one' => '{0} grau Celsius', 'other' => '{0} graus Celsius'], 'perUnit' => ''], short: ['name' => 'graus Celsius', 'plurals' => ['one' => '{0} °C', 'other' => '{0} °C'], 'perUnit' => ''], narrow: ['name' => '°C', 'plurals' => ['one' => '{0}°C', 'other' => '{0}°C'], 'perUnit' => '']),
    'day' => new U(name: 'duration-day', long: ['name' => 'dias', 'plurals' => ['one' => '{0} dia', 'other' => '{0} dias'], 'perUnit' => '{0} por dia'], short: ['name' => 'dias', 'plurals' => ['one' => '{0} dia', 'other' => '{0} dias'], 'perUnit' => '{0}/dia'], narrow: ['name' => 'dia', 'plurals' => ['one' => '{0} dia', 'other' => '{0} dias'], 'perUnit' => '{0}/d']),
    'fahrenheit' => new U(name: 'temperature-fahrenheit', long: ['name' => 'graus Fahrenheit', 'plurals' => ['one' => '{0} grau Fahrenheit', 'other' => '{0} graus Fahrenheit'], 'perUnit' => ''], short: ['name' => 'graus Fahrenheit', 'plurals' => ['one' => '{0} °F', 'other' => '{0} °F'], 'perUnit' => ''], narrow: ['name' => '°F', 'plurals' => ['one' => '{0} °F', 'other' => '{0} °F'], 'perUnit' => '']),
    'fluid-ounce' => new U(name: 'volume-fluid-ounce', long: ['name' => 'onças fluidas', 'plurals' => ['one' => '{0} onça fluida', 'other' => '{0} onças fluidas'], 'perUnit' => ''], short: ['name' => 'fl oz', 'plurals' => ['one' => '{0} fl oz', 'other' => '{0} fl oz'], 'perUnit' => ''], narrow: ['name' => 'fl oz', 'plurals' => ['one' => '{0} fl oz', 'other' => '{0} fl oz'], 'perUnit' => '']),
    'foot' => new U(name: 'length-foot', long: ['name' => 'pés', 'plurals' => ['one' => '{0} pé', 'other' => '{0} pés'], 'perUnit' => '{0} por pé'], short: ['name' => 'pés', 'plurals' => ['one' => '{0} pé', 'other' => '{0} pés'], 'perUnit' => '{0}/pé'], narrow: ['name' => 'pés', 'plurals' => ['one' => '{0}′', 'other' => '{0}′'], 'perUnit' => '{0}/pé']),
    'gram' => new U(name: 'mass-gram', long: ['name' => 'gramas', 'plurals' => ['one' => '{0} grama', 'other' => '{0} gramas'], 'perUnit' => '{0} por grama'], short: ['name' => 'gramas', 'plurals' => ['one' => '{0} g', 'other' => '{0} g'], 'perUnit' => '{0}/g'], narrow: ['name' => 'grama', 'plurals' => ['one' => '{0} g', 'other' => '{0} g'], 'perUnit' => '{0}/g']),
    'hour' => new U(name: 'duration-hour', long: ['name' => 'horas', 'plurals' => ['one' => '{0} hora', 'other' => '{0} horas'], 'perUnit' => '{0}/h'], short: ['name' => 'horas', 'plurals' => ['one' => '{0} h', 'other' => '{0} h'], 'perUnit' => '{0}/h'], narrow: ['name' => 'hora', 'plurals' => ['one' => '{0} h', 'other' => '{0} h'], 'perUnit' => '{0}/h']),
    'inch' => new U(name: 'length-inch', long: ['name' => 'polegadas', 'plurals' => ['one' => '{0} polegada', 'other' => '{0} polegadas'], 'perUnit' => '{0} por polegada'], short: ['name' => 'polegadas', 'plurals' => ['one' => '{0} pol.', 'other' => '{0} pol.'], 'perUnit' => '{0}/pol.'], narrow: ['name' => 'pol.', 'plurals' => ['one' => '{0}″', 'other' => '{0}″'], 'perUnit' => '{0}/pol.']),
    'kilogram' => new U(name: 'mass-kilogram', long: ['name' => 'quilogramas', 'plurals' => ['one' => '{0} quilograma', 'other' => '{0} quilogramas'], 'perUnit' => '{0} por quilograma'], short: ['name' => 'kg', 'plurals' => ['one' => '{0} kg', 'other' => '{0} kg'], 'perUnit' => '{0}/kg'], narrow: ['name' => 'kg', 'plurals' => ['one' => '{0} kg', 'other' => '{0} kg'], 'perUnit' => '{0}/kg']),
    'kilometer' => new U(name: 'length-kilometer', long: ['name' => 'quilómetros', 'plurals' => ['one' => '{0} quilómetro', 'other' => '{0} quilómetros'], 'perUnit' => '{0} por quilómetro'], short: ['name' => 'km', 'plurals' => ['one' => '{0} km', 'other' => '{0} km'], 'perUnit' => '{0}/km'], narrow: ['name' => 'km', 'plurals' => ['one' => '{0} km', 'other' => '{0} km'], 'perUnit' => '{0}/km']),
    'liter' => new U(name: 'volume-liter', long: ['name' => 'litros', 'plurals' => ['one' => '{0} litro', 'other' => '{0} litros'], 'perUnit' => '{0} por litro'], short: ['name' => 'litros', 'plurals' => ['one' => '{0} l', 'other' => '{0} l'], 'perUnit' => '{0}/l'], narrow: ['name' => 'litro', 'plurals' => ['one' => '{0} l', 'other' => '{0} l'], 'perUnit' => '{0}/l']),
    'meter' => new U(name: 'length-meter', long: ['name' => 'metros', 'plurals' => ['one' => '{0} metro', 'other' => '{0} metros'], 'perUnit' => '{0} por metro'], short: ['name' => 'metros', 'plurals' => ['one' => '{0} m', 'other' => '{0} m'], 'perUnit' => '{0}/m'], narrow: ['name' => 'metro', 'plurals' => ['one' => '{0} m', 'other' => '{0} m'], 'perUnit' => '{0}/m']),
    'mile' => new U(name: 'length-mile', long: ['name' => 'milhas', 'plurals' => ['one' => '{0} milha', 'other' => '{0} milhas'], 'perUnit' => ''], short: ['name' => 'milhas', 'plurals' => ['one' => '{0} milha', 'other' => '{0} milhas'], 'perUnit' => ''], narrow: ['name' => 'milha', 'plurals' => ['one' => '{0} milha', 'other' => '{0} milhas'], 'perUnit' => '']),
    'mile-scandinavian' => new U(name: 'length-mile-scandinavian', long: ['name' => 'milha escandinava', 'plurals' => ['one' => '{0} milha escandinava', 'other' => '{0} milhas escandinavas'], 'perUnit' => ''], short: ['name' => 'smi', 'plurals' => ['one' => '{0} smi', 'other' => '{0} smi'], 'perUnit' => ''], narrow: ['name' => 'smi', 'plurals' => ['one' => '{0} smi', 'other' => '{0} smi'], 'perUnit' => '']),
    'minute' => new U(name: 'duration-minute', long: ['name' => 'minutos', 'plurals' => ['one' => '{0} minuto', 'other' => '{0} minutos'], 'perUnit' => '{0} por minuto'], short: ['name' => 'minutos', 'plurals' => ['one' => '{0} min', 'other' => '{0} min'], 'perUnit' => '{0}/min'], narrow: ['name' => 'min', 'plurals' => ['one' => '{0} min', 'other' => '{0} min'], 'perUnit' => '{0}/min']),
    'second' => new U(name: 'duration-second', long: ['name' => 'segundos', 'plurals' => ['one' => '{0} segundo', 'other' => '{0} segundos'], 'perUnit' => '{0}/s'], short: ['name' => 's', 'plurals' => ['one' => '{0} s', 'other' => '{0} s'], 'perUnit' => '{0}/s'], narrow: ['name' => 's', 'plurals' => ['one' => '{0} s', 'other' => '{0} s'], 'perUnit' => '{0}/s']),
];
