<?php

use Major\Fluent\Formatters\Number\Locale\Unit as U;

return [
    'acre' => new U(name: 'area-acre', long: ['name' => 'acre', 'plurals' => ['other' => '{0} ac'], 'perUnit' => ''], short: ['name' => 'acre', 'plurals' => ['other' => '{0} ac'], 'perUnit' => ''], narrow: ['name' => 'acre', 'plurals' => ['other' => '{0}ac'], 'perUnit' => '']),
    'bit' => new U(name: 'digital-bit', long: ['name' => 'àwọ́n bíìtì', 'plurals' => ['other' => '{0} àwọ́n bíìtì'], 'perUnit' => ''], short: ['name' => 'bíìtì', 'plurals' => ['other' => '{0} bíìtì'], 'perUnit' => ''], narrow: ['name' => 'bit', 'plurals' => ['other' => '{0}bíìtì'], 'perUnit' => '']),
    'byte' => new U(name: 'digital-byte', long: ['name' => 'àwọ́n báìtì', 'plurals' => ['other' => '{0} àwọ́n báìtì'], 'perUnit' => ''], short: ['name' => 'báìtì', 'plurals' => ['other' => '{0} báìtì'], 'perUnit' => ''], narrow: ['name' => 'B', 'plurals' => ['other' => '{0}B'], 'perUnit' => '']),
    'day' => new U(name: 'duration-day', long: ['name' => 'ọjọ́', 'plurals' => ['other' => 'ọj {0}'], 'perUnit' => '{0}/ọj'], short: ['name' => 'ọjọ́', 'plurals' => ['other' => '{0} ọj'], 'perUnit' => '{0}/ọj'], narrow: ['name' => 'ọjọ́', 'plurals' => ['other' => 'ọj {0}'], 'perUnit' => '{0}/ọj']),
    'fahrenheit' => new U(name: 'temperature-fahrenheit', long: ['name' => '°F', 'plurals' => ['other' => '{0}°F'], 'perUnit' => ''], short: ['name' => '°F', 'plurals' => ['other' => '{0}°F'], 'perUnit' => ''], narrow: ['name' => '°F', 'plurals' => ['other' => '{0}°'], 'perUnit' => '']),
    'fluid-ounce' => new U(name: 'volume-fluid-ounce', long: ['name' => 'US fl oz', 'plurals' => ['other' => '{0} fl oz US'], 'perUnit' => ''], short: ['name' => 'US fl oz', 'plurals' => ['other' => '{0} fl oz US'], 'perUnit' => ''], narrow: ['name' => 'fl oz', 'plurals' => ['other' => '{0}fl oz'], 'perUnit' => '']),
    'gallon' => new U(name: 'volume-gallon', long: ['name' => 'US gal', 'plurals' => ['other' => '{0} gal US'], 'perUnit' => '{0}/gal US'], short: ['name' => 'US gal', 'plurals' => ['other' => '{0} gal US'], 'perUnit' => '{0}/gal US'], narrow: ['name' => 'gal', 'plurals' => ['other' => '{0}gal'], 'perUnit' => '{0}/gal']),
    'gigabit' => new U(name: 'digital-gigabit', long: ['name' => 'àwọn gígábíìtì', 'plurals' => ['other' => '{0} àwọn gígábíìtì'], 'perUnit' => ''], short: ['name' => 'jíbíìtì', 'plurals' => ['other' => '{0}jíbíìtì'], 'perUnit' => ''], narrow: ['name' => 'Gb', 'plurals' => ['other' => '{0}Gb'], 'perUnit' => '']),
    'gigabyte' => new U(name: 'digital-gigabyte', long: ['name' => 'àwọn gígábáìtì', 'plurals' => ['other' => '{0} àwọn gígábáìtì'], 'perUnit' => ''], short: ['name' => 'jíbáìtì', 'plurals' => ['other' => '{0} jíbáìtì'], 'perUnit' => ''], narrow: ['name' => 'GB', 'plurals' => ['other' => '{0}GB'], 'perUnit' => '']),
    'hectare' => new U(name: 'area-hectare', long: ['name' => 'hectare', 'plurals' => ['other' => '{0} ha'], 'perUnit' => ''], short: ['name' => 'hectare', 'plurals' => ['other' => '{0} ha'], 'perUnit' => ''], narrow: ['name' => 'hectare', 'plurals' => ['other' => '{0}ha'], 'perUnit' => '']),
    'hour' => new U(name: 'duration-hour', long: ['name' => 'wkt', 'plurals' => ['other' => '{0} wkt'], 'perUnit' => '{0}/wkt'], short: ['name' => 'wkt', 'plurals' => ['other' => '{0} wkt'], 'perUnit' => '{0}/wkt'], narrow: ['name' => 'wkt', 'plurals' => ['other' => '{0} wkt'], 'perUnit' => '{0}/wkt']),
    'kilobit' => new U(name: 'digital-kilobit', long: ['name' => 'àwọn kílóbíìtì', 'plurals' => ['other' => '{0} àwọ́n kílóbíìtì'], 'perUnit' => ''], short: ['name' => 'kébiì', 'plurals' => ['other' => '{0} kébiì'], 'perUnit' => ''], narrow: ['name' => 'kb', 'plurals' => ['other' => '{0}kb'], 'perUnit' => '']),
    'kilobyte' => new U(name: 'digital-kilobyte', long: ['name' => 'àwọn kílóbáìtì', 'plurals' => ['other' => '{0} àwọn kílóbáìtì'], 'perUnit' => ''], short: ['name' => 'kébáìtì', 'plurals' => ['other' => '{0} kébáìtì'], 'perUnit' => ''], narrow: ['name' => 'kB', 'plurals' => ['other' => '{0}kB'], 'perUnit' => '']),
    'liter' => new U(name: 'volume-liter', long: ['name' => 'liter', 'plurals' => ['other' => '{0} l'], 'perUnit' => '{0}/l'], short: ['name' => 'liter', 'plurals' => ['other' => '{0} l'], 'perUnit' => '{0}/l'], narrow: ['name' => 'liter', 'plurals' => ['other' => '{0} l'], 'perUnit' => '{0}/L']),
    'megabit' => new U(name: 'digital-megabit', long: ['name' => 'àwọn mégábíìtì', 'plurals' => ['other' => '{0} àwọn mégábíìtì'], 'perUnit' => ''], short: ['name' => 'ẹ́mbíìtì', 'plurals' => ['other' => '{0} ẹ́mbiì'], 'perUnit' => ''], narrow: ['name' => 'Mb', 'plurals' => ['other' => '{0}Mb'], 'perUnit' => '']),
    'megabyte' => new U(name: 'digital-megabyte', long: ['name' => 'àwọn mégábáìtì', 'plurals' => ['other' => '{0} àwọn mégábáìtì'], 'perUnit' => ''], short: ['name' => 'ẹ́mbáìtì', 'plurals' => ['other' => '{0} MB'], 'perUnit' => ''], narrow: ['name' => 'MB', 'plurals' => ['other' => '{0}MB'], 'perUnit' => '']),
    'milliliter' => new U(name: 'volume-milliliter', long: ['name' => 'mL', 'plurals' => ['other' => '{0} mL'], 'perUnit' => ''], short: ['name' => 'mL', 'plurals' => ['other' => '{0} mL'], 'perUnit' => ''], narrow: ['name' => 'mL', 'plurals' => ['other' => '{0}mL'], 'perUnit' => '']),
    'minute' => new U(name: 'duration-minute', long: ['name' => 'ìṣ', 'plurals' => ['other' => '{0} ìṣ'], 'perUnit' => '{0}/ìṣ'], short: ['name' => 'ìṣ', 'plurals' => ['other' => '{0} ìṣ'], 'perUnit' => '{0}/ìṣ'], narrow: ['name' => 'ìṣ', 'plurals' => ['other' => '{0}/ìṣ'], 'perUnit' => '{0}/ìṣ']),
    'month' => new U(name: 'duration-month', long: ['name' => 'oṣù', 'plurals' => ['other' => '{0} oṣù'], 'perUnit' => '{0}/oṣù'], short: ['name' => 'oṣù', 'plurals' => ['other' => '{0} oṣù'], 'perUnit' => '{0}/oṣù'], narrow: ['name' => 'oṣù', 'plurals' => ['other' => '{0} oṣù'], 'perUnit' => '{0}/oṣù']),
    'ounce' => new U(name: 'mass-ounce', long: ['name' => 'oz', 'plurals' => ['other' => '{0} oz'], 'perUnit' => '{0}/oz'], short: ['name' => 'oz', 'plurals' => ['other' => '{0} oz'], 'perUnit' => '{0}/oz'], narrow: ['name' => 'oz', 'plurals' => ['other' => '{0}oz'], 'perUnit' => '{0}/oz']),
    'petabyte' => new U(name: 'digital-petabyte', long: ['name' => 'àwọn pẹ́tábáìtì', 'plurals' => ['other' => '{0} àwọn pẹ́tábáìtì'], 'perUnit' => ''], short: ['name' => 'Píbáìtì', 'plurals' => ['other' => '{0} Píbáìtì'], 'perUnit' => ''], narrow: ['name' => 'PB', 'plurals' => ['other' => '{0}PB'], 'perUnit' => '']),
    'second' => new U(name: 'duration-second', long: ['name' => 'ìṣ àáy', 'plurals' => ['other' => '{0}ìṣ àáy'], 'perUnit' => '{0}/ìṣ àáy'], short: ['name' => 'ìṣ àáy', 'plurals' => ['other' => '{0} ìṣ àáy'], 'perUnit' => '{0} ìṣ àáy'], narrow: ['name' => 'ìṣ àáy', 'plurals' => ['other' => '{0} ìṣ àáy'], 'perUnit' => '{0} ìṣ àáy']),
    'stone' => new U(name: 'mass-stone', long: ['name' => 'àwon okùta', 'plurals' => ['other' => '{0} àwon okùta'], 'perUnit' => ''], short: ['name' => 'àwon okùta', 'plurals' => ['other' => '{0} st'], 'perUnit' => ''], narrow: ['name' => 'okùta', 'plurals' => ['other' => '{0}st'], 'perUnit' => '']),
    'terabit' => new U(name: 'digital-terabit', long: ['name' => 'àwọn tẹ́rábíìtì', 'plurals' => ['other' => '{0} àwọn tẹ́rábíìtì'], 'perUnit' => ''], short: ['name' => 'Tb', 'plurals' => ['other' => '{0} Tb'], 'perUnit' => ''], narrow: ['name' => 'Tb', 'plurals' => ['other' => '{0}Tb'], 'perUnit' => '']),
    'terabyte' => new U(name: 'digital-terabyte', long: ['name' => 'àwọn tẹ́rábáìtì', 'plurals' => ['other' => '{0} àwọn tẹ́rábáìtì'], 'perUnit' => ''], short: ['name' => 'Tíbáìtì', 'plurals' => ['other' => '{0} Tíbáìtì'], 'perUnit' => ''], narrow: ['name' => 'TB', 'plurals' => ['other' => '{0}TB'], 'perUnit' => '']),
    'week' => new U(name: 'duration-week', long: ['name' => 'ọṣ', 'plurals' => ['other' => '{0} ọṣ'], 'perUnit' => '{0}/ọṣ'], short: ['name' => 'ọṣ', 'plurals' => ['other' => '{0} ọṣ'], 'perUnit' => '{0}/ọṣẹ̀'], narrow: ['name' => 'ọṣẹ́', 'plurals' => ['other' => '{0} ọṣ'], 'perUnit' => '{0}/ọ̀ṣẹ̀']),
    'year' => new U(name: 'duration-year', long: ['name' => 'ọ̀dún', 'plurals' => ['other' => '{0} ọd'], 'perUnit' => '{0} ọd'], short: ['name' => 'ọd', 'plurals' => ['other' => '{0} ọd'], 'perUnit' => '{0}/ọd'], narrow: ['name' => 'ọd', 'plurals' => ['other' => '{0} ọd'], 'perUnit' => '{0}/ọd']),
];
