<?php

use Major\Fluent\Formatters\Number\Locale\Unit as U;

return [
    'acre' => new U(name: 'area-acre', long: ['name' => '英亩', 'plurals' => ['other' => '{0} 英亩'], 'perUnit' => ''], short: ['name' => '英亩', 'plurals' => ['other' => '{0} 英亩'], 'perUnit' => ''], narrow: ['name' => '英亩', 'plurals' => ['other' => '{0} 英亩'], 'perUnit' => '']),
    'hectare' => new U(name: 'area-hectare', long: ['name' => '公顷', 'plurals' => ['other' => '{0} 公顷'], 'perUnit' => ''], short: ['name' => '公顷', 'plurals' => ['other' => '{0} 公顷'], 'perUnit' => ''], narrow: ['name' => '公顷', 'plurals' => ['other' => '{0} 公顷'], 'perUnit' => '']),
    'byte' => new U(name: 'digital-byte', long: ['name' => 'byte', 'plurals' => ['other' => '{0} byte'], 'perUnit' => ''], short: ['name' => 'byte', 'plurals' => ['other' => '{0} byte'], 'perUnit' => ''], narrow: ['name' => 'B', 'plurals' => ['other' => '{0}byte'], 'perUnit' => '']),
    'day' => new U(name: 'duration-day', long: ['name' => '天', 'plurals' => ['other' => '{0} 天'], 'perUnit' => '每日 {0}'], short: ['name' => '天', 'plurals' => ['other' => '{0} 天'], 'perUnit' => '每日{0}'], narrow: ['name' => '天', 'plurals' => ['other' => '{0} 天'], 'perUnit' => '每日{0}']),
    'hour' => new U(name: 'duration-hour', long: ['name' => '小时', 'plurals' => ['other' => '{0} 小时'], 'perUnit' => '每小时 {0}'], short: ['name' => '小时', 'plurals' => ['other' => '{0} 小时'], 'perUnit' => '每小时{0}'], narrow: ['name' => '小时', 'plurals' => ['other' => '{0} 小时'], 'perUnit' => '每小时{0}']),
    'minute' => new U(name: 'duration-minute', long: ['name' => '分钟', 'plurals' => ['other' => '{0} 分钟'], 'perUnit' => '每分钟 {0}'], short: ['name' => '分钟', 'plurals' => ['other' => '{0} 分钟'], 'perUnit' => '每分钟{0}'], narrow: ['name' => '分钟', 'plurals' => ['other' => '{0} 分钟'], 'perUnit' => '每分钟{0}']),
    'month' => new U(name: 'duration-month', long: ['name' => '月', 'plurals' => ['other' => '{0} 个月'], 'perUnit' => '每月 {0}'], short: ['name' => '月', 'plurals' => ['other' => '{0} 个月'], 'perUnit' => '每月{0}'], narrow: ['name' => '月', 'plurals' => ['other' => '{0} 个月'], 'perUnit' => '每月{0}']),
    'week' => new U(name: 'duration-week', long: ['name' => '周', 'plurals' => ['other' => '{0} 周'], 'perUnit' => '每星期 {0}'], short: ['name' => '周', 'plurals' => ['other' => '{0} 周'], 'perUnit' => '每周{0}'], narrow: ['name' => '周', 'plurals' => ['other' => '{0} 周'], 'perUnit' => '每周{0}']),
    'centimeter' => new U(name: 'length-centimeter', long: ['name' => '公分', 'plurals' => ['other' => '{0} 公分'], 'perUnit' => '每厘米 {0}'], short: ['name' => '公分', 'plurals' => ['other' => '{0} 公分'], 'perUnit' => '每厘米{0}'], narrow: ['name' => '公分', 'plurals' => ['other' => '{0} 公分'], 'perUnit' => '每厘米{0}']),
    'foot' => new U(name: 'length-foot', long: ['name' => '英尺', 'plurals' => ['other' => '{0} 英尺'], 'perUnit' => '每呎 {0}'], short: ['name' => '英尺', 'plurals' => ['other' => '{0} 呎'], 'perUnit' => '每呎{0}'], narrow: ['name' => '英尺', 'plurals' => ['other' => '{0} 呎'], 'perUnit' => '每呎{0}']),
    'inch' => new U(name: 'length-inch', long: ['name' => '英寸', 'plurals' => ['other' => '{0} 英寸'], 'perUnit' => '每吋 {0}'], short: ['name' => '英寸', 'plurals' => ['other' => '{0} 吋'], 'perUnit' => '每吋{0}'], narrow: ['name' => '英寸', 'plurals' => ['other' => '{0} 吋'], 'perUnit' => '每英寸 {0}']),
    'meter' => new U(name: 'length-meter', long: ['name' => '公尺', 'plurals' => ['other' => '{0} 公尺'], 'perUnit' => '每米 {0}'], short: ['name' => '公尺', 'plurals' => ['other' => '{0} 公尺'], 'perUnit' => '每米{0}'], narrow: ['name' => '公尺', 'plurals' => ['other' => '{0} 公尺'], 'perUnit' => '每米{0}']),
    'mile-scandinavian' => new U(name: 'length-mile-scandinavian', long: ['name' => '斯堪地那维亚英里', 'plurals' => ['other' => '{0} 斯堪地那维亚英里'], 'perUnit' => ''], short: ['name' => '斯堪地那维亚英里', 'plurals' => ['other' => '{0} 斯堪地那维亚英里'], 'perUnit' => ''], narrow: ['name' => '斯堪地那维亚英里', 'plurals' => ['other' => '{0} 斯堪地那维亚英里'], 'perUnit' => '']),
    'millimeter' => new U(name: 'length-millimeter', long: ['name' => '公厘', 'plurals' => ['other' => '{0} 公厘'], 'perUnit' => ''], short: ['name' => '公厘', 'plurals' => ['other' => '{0} 公厘'], 'perUnit' => ''], narrow: ['name' => '公厘', 'plurals' => ['other' => '{0} 公厘'], 'perUnit' => '']),
    'yard' => new U(name: 'length-yard', long: ['name' => '码', 'plurals' => ['other' => '{0} 码'], 'perUnit' => ''], short: ['name' => '码', 'plurals' => ['other' => '{0} 码'], 'perUnit' => ''], narrow: ['name' => '码', 'plurals' => ['other' => '{0} 码'], 'perUnit' => '']),
    'ounce' => new U(name: 'mass-ounce', long: ['name' => '盎司', 'plurals' => ['other' => '{0} 盎司'], 'perUnit' => '每安士 {0}'], short: ['name' => '盎司', 'plurals' => ['other' => '{0} 盎司'], 'perUnit' => '每安士{0}'], narrow: ['name' => '盎司', 'plurals' => ['other' => '{0} 盎司'], 'perUnit' => '每安士 {0}']),
    'stone' => new U(name: 'mass-stone', long: ['name' => '英石', 'plurals' => ['other' => '{0} 英石'], 'perUnit' => ''], short: ['name' => 'st', 'plurals' => ['other' => '{0} 英石'], 'perUnit' => ''], narrow: ['name' => '英石', 'plurals' => ['other' => '{0} 英石'], 'perUnit' => '']),
    'celsius' => new U(name: 'temperature-celsius', long: ['name' => '摄氏度数', 'plurals' => ['other' => '摄氏 {0} 度'], 'perUnit' => ''], short: ['name' => '摄氏', 'plurals' => ['other' => '{0}°C'], 'perUnit' => ''], narrow: ['name' => '°C', 'plurals' => ['other' => '{0}°C'], 'perUnit' => '']),
    'fahrenheit' => new U(name: 'temperature-fahrenheit', long: ['name' => '华氏度数', 'plurals' => ['other' => '华氏 {0} 度'], 'perUnit' => ''], short: ['name' => '华氏', 'plurals' => ['other' => '{0}°F'], 'perUnit' => ''], narrow: ['name' => '华氏', 'plurals' => ['other' => '{0}°F'], 'perUnit' => '']),
    'gallon' => new U(name: 'volume-gallon', long: ['name' => '加仑', 'plurals' => ['other' => '{0} 加仑'], 'perUnit' => '每加仑 {0}'], short: ['name' => '加仑', 'plurals' => ['other' => '{0} 加仑'], 'perUnit' => '每加仑{0}'], narrow: ['name' => '加仑', 'plurals' => ['other' => '{0} 加仑'], 'perUnit' => '每加仑{0}']),
    'liter' => new U(name: 'volume-liter', long: ['name' => '公升', 'plurals' => ['other' => '{0} 公升'], 'perUnit' => '每公升 {0}'], short: ['name' => '公升', 'plurals' => ['other' => '{0} 升'], 'perUnit' => '每升{0}'], narrow: ['name' => '公升', 'plurals' => ['other' => '{0} 升'], 'perUnit' => '每升{0}']),
];
